### PR TITLE
[Raja] problem statement

### PR DESCRIPTION
**Pull request by srajas0**

### CODE REVIEW

**Comment by srajas0** [comment]
@callmekatootie Please review this PR.

**Comment by callmekatootie** [comment]
Issue 1:

The header (for this page only) seems a bit weird

EXPECTED:
image

ACTUAL
image

**Comment by callmekatootie** [comment]
Issue 2: The background is not matching design.

Design:
image

ACTUAL:
image

**Comment by callmekatootie** [comment]
@srajas0 review completed. 2 issues observed

**Pull request merged**
