### PR TITLE
#42 Winners Page | Update page to match design

### PR DESCRIPTION
**Pull request by suppermancool**
#42 Winners Page | Update page to match design

### CODE REVIEW

**Comment by callmekatootie** [comment]
EXPECTED:
image

ACTUAL:

image

The middle cup seems to be on the same level as the others. It should be higher as seen in design

**Comment by callmekatootie** [comment]
There's another issue - check out the finalist details page. Right now, its displaying fine - but with your changes, we see 2 rows for the finalists (there should only be 1)

**Comment by suppermancool** [comment]
> There's another issue - check out the finalist details page. Right now, its displaying fine - but with your changes, we see 2 rows for the finalists (there should only be 1)

@callmekatootie you mean this https://gyazo.com/43c78fca71777f9de18f99f214129959 right? I updated this to match with design. You mean we only have one row (`Finalists`) right?

**Comment by callmekatootie** [comment]
No i mean another page - see url and see the finalists row at the bottom - it should be one one page only. It displays fine now, but with your changes it appears to get affected

image

**Comment by suppermancool** [comment]
https://github.com/topcoder-platform/leaderboard-ui/pull/44#issuecomment-549040401

@callmekatootie sorry i didn't get this. I didn't change any code in this page, and the behavior of this page is same as commit a476ed9 (i worked from this commit) in develop branch. This is what happen in commit a476ed9

https://gyazo.com/73971143e00355a75b005857b98ac839

**Comment by suppermancool** [comment]
@callmekatootie this https://github.com/topcoder-platform/leaderboard-ui/pull/44#issuecomment-549036257 done in the latest commit

**Comment by callmekatootie** [comment]
Yeah - I cannot reproduce that issue consistently too... we can ignore it for now I guess

**Pull request merged**
